//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using Unity.Entities;
using Unity.NetCode;
#region __GHOST_USING_STATEMENT__
using __GHOST_USING__;
#endregion

#region __END_HEADER__
#endregion
namespace __GHOST_NAMESPACE__
{
    [UpdateInGroup(typeof(ClientAndServerInitializationSystemGroup))]
    public class GhostComponentSerializerRegistrationSystem : SystemBase
    {
        protected override void OnCreate()
        {
            var ghostCollectionSystem = World.GetOrCreateSystem<GhostCollectionSystem>();
            #region __GHOST_COMPONENT_LIST__
            ghostCollectionSystem.AddSerializer(__GHOST_NAME__GhostComponentSerializer.State);
            #endregion
        }

        protected override void OnUpdate()
        {
            var parentGroup = World.GetExistingSystem<InitializationSystemGroup>();
            if (parentGroup != null)
            {
                parentGroup.RemoveSystemFromUpdateList(this);
            }
        }
    }
}