//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using Unity.Burst;
#region __GHOST_USING_STATEMENT__
using __GHOST_USING__;
#endregion

namespace __GHOST_NAMESPACE__
{
    [BurstCompile]
    [System.Runtime.CompilerServices.CompilerGenerated]
    [CreateAfter(typeof(GhostComponentSerializerCollectionSystemGroup))]
    [UpdateInGroup(typeof(GhostComponentSerializerCollectionSystemGroup))]
    public struct __REGISTRATION_SYSTEM_FILE_NAME__ : ISystem
    {
        [BurstCompile]
        public void OnCreate(ref Unity.Entities.SystemState state)
        {
            // Manual query as `SystemAPI.GetSingletonRW<GhostComponentSerializerCollectionData>()` is throwing "fail to compile" errors.
            using var builder = new EntityQueryBuilder(Allocator.Temp).WithAllRW<GhostComponentSerializerCollectionData>();
            using var query = state.EntityManager.CreateEntityQuery(builder);
            ref var data = ref query.GetSingletonRW<GhostComponentSerializerCollectionData>().ValueRW;

            #region __GHOST_META_DATA_LIST__
            data.AddCodeGenTypeMetaData(new CodeGenTypeMetaData
            {
                TypeHash = __VARIANT_TYPE_HASH__,
                IsInputComponent = __TYPE_IS_INPUT_COMPONENT__,
                IsInputBuffer = __TYPE_IS_INPUT_BUFFER__,
                IsTestVariant = __TYPE_IS_TEST_VARIANT__,
                HasDontSupportPrefabOverridesAttribute = __TYPE_HAS_DONT_SUPPORT_PREFAB_OVERRIDES_ATTRIBUTE__,
                HasSupportsPrefabOverridesAttribute = __TYPE_HAS_SUPPORTS_PREFAB_OVERRIDES_ATTRIBUTE__,
            });
            #endregion
        }

        [BurstCompile]
        public void OnUpdate(ref Unity.Entities.SystemState state)
        {
        }

        [BurstCompile]
        public void OnDestroy(ref Unity.Entities.SystemState state)
        {
        }
    }
}
