//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using Unity.Entities;
using Unity.NetCode;
using Unity.NetCode.LowLevel.Unsafe;
#region __GHOST_USING_STATEMENT__
using __GHOST_USING__;
#endregion

#region __GHOST_END_HEADER__
#endregion
namespace __GHOST_NAMESPACE__
{
    [System.Runtime.CompilerServices.CompilerGenerated]
    [UpdateInGroup(typeof(GhostComponentSerializerCollectionSystemGroup))]
    [CreateAfter(typeof(GhostComponentSerializerCollectionSystemGroup))]
    public class GhostComponentSerializerRegistrationSystem : GhostComponentSerializerRegistrationSystemBase
    {
        protected override void OnCreate()
        {
            ref var data = ref GetSingletonRW<GhostComponentSerializerCollectionData>().ValueRW;
            #region __GHOST_COMPONENT_LIST__
            data.AddSerializer(__GHOST_NAME__GhostComponentSerializer.State);
            #endregion
            #region __GHOST_EMPTY_VARIANT_LIST__
            data.AddEmptyVariant(new VariantType
            {
                Component = ComponentType.ReadWrite<__GHOST_COMPONENT_TYPE__>(),
                Hash = __GHOST_VARIANT_HASH__,
                PrefabType = __GHOST_PREFAB_TYPE__,
                VariantTypeIndex = GhostComponentSerializer.VariantTypes.Count,
            });
            GhostComponentSerializer.VariantTypes.Add(typeof(__VARIANT_TYPE__));
            #endregion
        }

        protected override void OnUpdate()
        {
        }
    }
}
