//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using Unity.Entities;
using Unity.NetCode;
#region __GHOST_USING_STATEMENT__
using __GHOST_USING__;
#endregion

#region __GHOST_END_HEADER__
#endregion
namespace __GHOST_NAMESPACE__
{
    [System.Runtime.CompilerServices.CompilerGenerated]
    [WorldSystemFilter(WorldSystemFilterFlags.Default | WorldSystemFilterFlags.GameObjectConversion)]
    [UpdateInGroup(typeof(GhostComponentSerializerCollectionSystemGroup))]
    public class GhostComponentSerializerRegistrationSystem : GhostComponentSerializerRegistrationSystemBase
    {
        protected override void OnCreate()
        {
            var ghostCollectionSystem = World.GetOrCreateSystem<GhostComponentSerializerCollectionSystemGroup>();
            #region __GHOST_COMPONENT_LIST__
            ghostCollectionSystem.AddSerializer(__GHOST_NAME__GhostComponentSerializer.State);
            #endregion
            #region __GHOST_EMPTY_VARIANT_LIST__
            ghostCollectionSystem.AddEmptyVariant(new VariantType
            {
                Component = ComponentType.ReadWrite<__GHOST_COMPONENT_TYPE__>(),
                Variant = typeof(__VARIANT_TYPE__),
                Hash = __GHOST_VARIANT_HASH__
            });
            #endregion
        }

        protected override void OnUpdate()
        {
        }
    }
}
