using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Unity.Netcode.Generators
{
    /// <summary>
    /// Back-compat for user extension files still declared in the renamed Unity.NetCode namespaces and compiled
    /// into the Unity.NetCode assembly via an .asmref. Namespace declarations cannot be rewritten by the
    /// ScriptUpdater, so the generator emits old-namespace scaffolding instead:
    /// - The Unity.NetCode.Generators.UserDefinedTemplates defining partial (plus TypeRegistryEntry and
    ///   SmoothingAction) when a legacy RegisterTemplates implementation is present.
    /// - GhostFieldSubType constants mirrored between Unity.NetCode and Unity.Netcode so both classes expose the union.
    /// </summary>
    internal static class NetCodeNamespaceCompat
    {
        const string k_LegacyRuntimeNamespace = "Unity.NetCode";
        const string k_LegacyGeneratorsNamespace = "Unity.NetCode.Generators";
        const string k_RuntimeNamespace = "Unity.Netcode";

        public static void Emit(GeneratorExecutionContext context, IDiagnosticReporter diagnostic)
        {
            if (context.Compilation.AssemblyName != "Unity.NetCode")
                return;

            var hasLegacyTemplates = false;
            var legacyConsts = new List<(string name, string initializer)>();
            var newConsts = new List<(string name, string initializer)>();
            var legacyConstNames = new HashSet<string>();
            var newConstNames = new HashSet<string>();

            foreach (var tree in context.Compilation.SyntaxTrees)
            {
                context.CancellationToken.ThrowIfCancellationRequested();
                foreach (var node in tree.GetRoot(context.CancellationToken).DescendantNodes())
                {
                    if (node is not ClassDeclarationSyntax cls)
                        continue;
                    switch (cls.Identifier.ValueText)
                    {
                        case "UserDefinedTemplates" when GetNamespace(cls) == k_LegacyGeneratorsNamespace:
                            foreach (var member in cls.Members)
                            {
                                if (member is MethodDeclarationSyntax { Identifier.ValueText: "RegisterTemplates", Body: not null })
                                {
                                    hasLegacyTemplates = true;
                                    diagnostic.LogWarning($"'{tree.FilePath}' declares UserDefinedTemplates in the renamed {k_LegacyGeneratorsNamespace} namespace. Compatibility scaffolding was generated; please move the declaration to the {k_RuntimeNamespace}.Generators namespace.");
                                }
                            }
                            break;
                        case "GhostFieldSubType" when GetNamespace(cls) == k_LegacyRuntimeNamespace:
                            CollectConsts(cls, legacyConsts, legacyConstNames);
                            diagnostic.LogWarning($"'{tree.FilePath}' declares GhostFieldSubType constants in the renamed {k_LegacyRuntimeNamespace} namespace. The constants were mirrored to {k_RuntimeNamespace}.GhostFieldSubType; please move the declaration to the {k_RuntimeNamespace} namespace.");
                            break;
                        case "GhostFieldSubType" when GetNamespace(cls) == k_RuntimeNamespace:
                            CollectConsts(cls, newConsts, newConstNames);
                            break;
                    }
                }
            }

            if (hasLegacyTemplates)
                context.AddSource("NetCodeNamespaceCompat.Templates.g.cs", SourceText.From(k_LegacyTemplatesScaffolding, Encoding.UTF8));

            if (legacyConsts.Count > 0)
            {
                var builder = new StringBuilder();
                builder.AppendLine("// <auto-generated>Mirrors GhostFieldSubType constants across the Unity.NetCode -> Unity.Netcode rename.</auto-generated>");
                AppendSubTypeMirror(builder, k_RuntimeNamespace, legacyConsts, newConstNames);
                AppendSubTypeMirror(builder, k_LegacyRuntimeNamespace, newConsts, legacyConstNames);
                context.AddSource("NetCodeNamespaceCompat.SubTypes.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
            }
        }

        static void AppendSubTypeMirror(StringBuilder builder, string targetNamespace, List<(string name, string initializer)> consts, HashSet<string> alreadyDeclared)
        {
            builder.AppendLine($"namespace {targetNamespace}");
            builder.AppendLine("{");
            builder.AppendLine("    public static partial class GhostFieldSubType");
            builder.AppendLine("    {");
            foreach (var (name, initializer) in consts)
            {
                if (!alreadyDeclared.Contains(name))
                    builder.AppendLine($"        public const int {name} = {initializer};");
            }
            builder.AppendLine("    }");
            builder.AppendLine("}");
        }

        static void CollectConsts(ClassDeclarationSyntax cls, List<(string name, string initializer)> consts, HashSet<string> names)
        {
            foreach (var member in cls.Members)
            {
                if (member is not FieldDeclarationSyntax field)
                    continue;
                var isConst = false;
                foreach (var modifier in field.Modifiers)
                    isConst |= modifier.IsKind(SyntaxKind.ConstKeyword);
                if (!isConst)
                    continue;
                foreach (var variable in field.Declaration.Variables)
                {
                    if (variable.Initializer == null)
                        continue;
                    var name = variable.Identifier.ValueText;
                    if (names.Add(name))
                        consts.Add((name, variable.Initializer.Value.ToString()));
                }
            }
        }

        static string GetNamespace(SyntaxNode node)
        {
            var parts = new List<string>();
            for (var parent = node.Parent; parent != null; parent = parent.Parent)
            {
                if (parent is BaseNamespaceDeclarationSyntax ns)
                    parts.Insert(0, ns.Name.ToString());
            }
            return string.Join(".", parts);
        }

        // Mirrors Runtime/Authoring/UserDefinedTemplates.cs and TypeRegistryEntry.cs in the renamed namespace.
        const string k_LegacyTemplatesScaffolding = @"// <auto-generated>Scaffolding for UserDefinedTemplates declared in the renamed Unity.NetCode.Generators namespace.</auto-generated>
namespace Unity.NetCode.Generators
{
    public enum SmoothingAction
    {
        Clamp = 0,
        Interpolate = 1,
        InterpolateAndExtrapolate = 3,
    }

    public class TypeRegistryEntry
    {
        public string Type;
        public string Template;
        public string TemplateOverride;
        public int SubType;
        public SmoothingAction Smoothing;
        public bool Quantized;
        public bool SupportCommand;
        public bool Composite;
    }

    public static partial class UserDefinedTemplates
    {
        internal static System.Collections.Generic.List<TypeRegistryEntry> Templates;

        static UserDefinedTemplates()
        {
            Templates = new System.Collections.Generic.List<TypeRegistryEntry>();
            RegisterTemplates(Templates, ""Packages/com.unity.netcode/Editor/Templates"");
        }
        static partial void RegisterTemplates(System.Collections.Generic.List<TypeRegistryEntry> templates, string defaultRootPath);
    }
}
";
    }
}
